### ISSUE TITLE
Unable to see menu

### ISSUE THREAD

**Issue by ajinkyagadewar** [sciCloud/OLiMS#1]
As of now only one menu is coming, can you please tell me what am I missing?

**Comment by avaughan** [comment]
This project is under development and not ready for public consumption.
 

Regards,
================================
John H. Jones
CEO - Laboratory Informatics Institute, Inc.
CEO - LabLynx, Inc.

Mailing Address:
P.O. Box 673966
Marietta, Georgia 30006

Physical Address:
2400 Lake Park Drive 
Suite 435
Smyrna, Georgia 30080
Map: http://g.co/maps/8u23b

Internet Address:
Email: mailto:jhjones@lablynx.com <mailto:jhjones@lablynx.com> 
Web: http://www.lablynx.com <http://www.lablynx.com/> 
Skype:  jhjones-lablynx
Linkedin: http://www.linkedin.com/in/johnhjones
 
Telephone:
V: 770-859-1992 x109
C: 770-312-9600
F: 877-832-4129
Conference Dial-in Number: (712) 432-0927 Access Code: 910768#
 

________________________________
