### ISSUE TITLE
Relation between Olims and Bika

### ISSUE THREAD

**Issue by vito80ba** [sciCloud/olims#6]
Hi,
it's not clear the relation between these software..
I'm a python dev and I'm exploring the "lims world" for a project... Bika is a complete solution plone based, while Olims is odoo  based.
In the source files of Olims I retrieve many references to bikalims.
Could you help me to clearify the situation?

**Comment by yasir1brahim** [comment]
Hi Vito,

We took Bika code which is based on Plone, and based on a defined scheme
changed it base to Odoo v9. Then we had to take a lot of different clean up
steps to make it workable. This is how OLiMS is developed from Bika.

Regards,

Yasir Ibrahim | Lead Software Architect & MD
[image: KNYSYS] <http://www.knysys.com>

US W +1-760-515-1663 | PK W +92-21-34972358 | PK M +92-321-3755312

Skype: yasiribrahim | Hangout: yasir.ibrahim | yibrahim@knysys.com

www.knysys.com | www.knyapps.com
